openweather.api.base-url=https://api.openweathermap.org
openweather.api.key=
openweather.api.timeout=5000

db.url=jdbc:postgresql://localhost:5432/weatherapp
db.username=
db.password=

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true