package dev.yoxaron.weather.repository;

import dev.yoxaron.weather.config.TestConfig;
import dev.yoxaron.weather.model.Session;
import dev.yoxaron.weather.model.User;
import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = TestConfig.class)
@Transactional
class SessionRepositoryTest {

    @Autowired
    private SessionRepository sessionRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    EntityManager entityManager;

    private User testUser;
    private Session testSession;

    @BeforeEach
    void setUp() {
        testUser = User.builder()
                .login("user1")
                .password("password1")
                .build();
        testUser = userRepository.save(testUser);

        testSession = Session.builder()
                .user(testUser)
                .expiresAt(LocalDateTime.now().plusHours(24))
                .build();
    }

    @Test
    void shouldFindAllSessions() {
        User user2 = userRepository.save(User.builder()
                .login("user2")
                .password("password2")
                .build());

        sessionRepository.save(testSession);
        sessionRepository.save(Session.builder()
                .user(user2)
                .expiresAt(LocalDateTime.now().plusHours(12))
                .build());

        List<Session> sessions = sessionRepository.findAll();

        assertThat(sessions).hasSize(2);
    }

    @Test
    void shouldSaveSessionWithAutoGeneratedUuid() {
        Session saved = sessionRepository.save(testSession);

        assertThat(saved).isNotNull();
        assertThat(saved.getId()).isNotNull();
        assertThat(saved.getId()).isInstanceOf(UUID.class);
        assertThat(saved.getUser().getId()).isEqualTo(testUser.getId());
        assertThat(saved.getExpiresAt()).isNotNull();
    }

    @Test
    void shouldFindSessionById() {
        Session saved = sessionRepository.save(testSession);
        UUID sessionId = saved.getId();

        Optional<Session> found = sessionRepository.findById(sessionId);

        assertThat(found).isPresent();
        assertThat(found.get().getId()).isEqualTo(sessionId);
        assertThat(found.get().getUser().getLogin()).isEqualTo("user1");
    }

    @Test
    void shouldFindSessionByUserId() {
        sessionRepository.save(testSession);

        List<Session> found = sessionRepository.findByUser(testUser);

        assertThat(found).isNotEmpty();
    }

    @Test
    void shouldUpdateSessionExpirationTime() {
        Session saved = sessionRepository.save(testSession);
        UUID sessionId = saved.getId();
        LocalDateTime newExpirationTime = LocalDateTime.now().plusHours(48);

        saved.setExpiresAt(newExpirationTime);
        sessionRepository.save(saved);

        Optional<Session> updated = sessionRepository.findById(sessionId);
        assertThat(updated).isPresent();
        assertThat(updated.get().getExpiresAt()).isEqualToIgnoringNanos(newExpirationTime);
    }

    @Test
    void shouldCascadeDeleteWhenUserDeleted() {
        Session saved = sessionRepository.save(testSession);
        UUID sessionId = saved.getId();

        userRepository.delete(testUser);

        entityManager.clear();

        Optional<Session> deletedSession = sessionRepository.findById(sessionId);
        assertThat(deletedSession).isEmpty();
    }
}
